// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // migrate/introspect usam conexão direta (não o pooler), que suporta os
  // locks de sessão que o motor de migration precisa. O app em runtime usa
  // o DATABASE_URL (pooled) via adapter, configurado em src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
